### PR TITLE
lot's and lot's of stuffs

### PR DESCRIPTION
**Pull request by stevenbristol**

### CODE REVIEW

**Comment by birarda** [comment]
Sorry for delay on this - was disconnected for a bit on vacation. I'll take a look at your two PRs sometime this week.

Thanks!

**Comment by stevenbristol** [comment]
We moved dev on this from my repo to LessEverything's repo.

**Comment by birarda** [comment]
Gotcha - so I can close #19 and just look at this one, right?

**Comment by stevenbristol** [comment]
Yeah. :)



Wishing you happiness,
Steven Bristol
Founder of LessAccounting <http://bit.ly/lessacc>

**Comment by AvaelKross** [comment]
+

**Comment by birarda** [comment]
out of curiosity, what was `activesupport` needed for in that?

**Comment by stevenbristol** [comment]
.blank?



Wishing you happiness,
Steven Bristol
Founder of LessAccounting <http://bit.ly/lessacc>

**Comment by birarda** [comment]
Got it, thanks. Would rather not require activesupport if we don't need to so I replaced that with `nil?` and then `empty?`

**Pull request merged**
